export const INVOICE_FIELD_CONFIG: any[] = [
  {
    key: 'vendorName',
    label: 'Vendor Name',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoicedEntity',
    label: 'Invoiced Entity',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoicedFundName',
    label: 'Invoiced Fund Name',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoiceNumber',
    label: 'Invoice No',
    type: 'text',
    group: 'Basic Information',
    editable: false,
  },
  {
    key: 'invoiceDate',
    label: 'Invoice Date',
    type: 'date',
    group: 'Basic Information',
    editable: true,
  },
  {
    key: 'vendorLocation',
    label: 'Vendor Location',
    type: 'text',
    group: 'Basic Information',
    editable: true,
  },
  {
    key: 'vendorCurrency',
    label: 'Vendor Ccy',
    type: 'text',
    group: 'Basic Information',
    editable: true,
  },
  { key: 'feeType', label: 'Fee type', type: 'text', group: 'Service Details', editable: true },
  {
    key: 'adminExpenses',
    label: 'Admin/Expences',
    type: 'text',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'invoiceNetAmount',
    label: 'Invoice Net Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
    required: true,
  },
  {
    key: 'invoiceTaxAmount',
    label: 'Invoice VAT amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'reverseChargeVATPaidByFirm',
    label: 'Reverse Charge VAT Paid by Firm',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'invoiceGrossAmount',
    label: 'Invoice Gross Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'invoiceAmountFundPortion',
    label: 'Invoice amount ( Fund Portion)',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'fxRate',
    label: 'FX(Per ECB Fixing on Invoice Date)',
    type: 'number',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'translatedAmountEUR',
    label: 'Translated Amount (EUR)',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'descriptionPerInvoice',
    label: 'Description Per Invoice',
    type: 'textarea',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'descriptionService',
    label: 'Description Service',
    type: 'textarea',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'classificationForAccounting',
    label: 'Classification for Accounting',
    type: 'text',
    group: 'Service Details',
    editable: true,
  },
  { key: 'paidBy', label: 'Paid By', type: 'text', group: 'Payment Information', editable: true },
  {
    key: 'amountPaid',
    label: 'Amount Paid',
    type: 'currency',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'reviewedBy',
    label: 'Reviewed By',
    type: 'textarea',
    group: 'Approval & Comments',
  },
  {
    key: 'approvedBy',
    label: 'Approved by',
    type: 'text',
    group: 'Approval & Comments',
    editable: true,
  },
  {
    key: 'sentFinanceBy',
    label: 'Sent to Finnance by',
    type: 'text',
    group: 'Approval & Comments',
    editable: true,
  },
  {
    key: 'sentToFinanceForPayment',
    label: 'Sent to Finance for Payment',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'dateSentToAdministratorForPayment',
    label: 'Date sent to administrator for payment',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'paymentDate',
    label: 'Payment Date',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'vatReturnEntity',
    label: 'VAT Return Entity',
    type: 'text',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatPaidByPanERO',
    label: 'VAT paid by pan ERO I',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatReturnPeriod',
    label: 'VAT Return Period',
    type: 'text',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatLiabilityAccruedAtEntity',
    label: 'VAT liability accrued at entity',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },

  { key: 'period', label: 'Period', type: 'text', group: 'Approval & Comments', editable: true },
  {
    key: 'financeComment',
    label: 'Finance Comment',
    type: 'textarea',
    group: 'Approval & Comments',
    editable: true,
  },
];
