export const INVOICE_FIELD_CONFIG: any[] = [
  // Basic Information
  {
    key: 'vendorName',
    label: 'Vendor Name',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoicedEntity',
    label: 'Invoiced Entity',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoicedFundName',
    label: 'Fund Name',
    type: 'text',
    group: 'Basic Information',
    editable: true,
    required: true,
  },
  {
    key: 'invoiceNumber',
    label: 'Invoice Number',
    type: 'text',
    group: 'Basic Information',
    editable: false,
  },
  {
    key: 'invoiceDate',
    label: 'Invoice Date',
    type: 'date',
    group: 'Basic Information',
    editable: true,
  },
  {
    key: 'vendorLocation',
    label: 'Vendor Location',
    type: 'text',
    group: 'Basic Information',
    editable: true,
  },
  {
    key: 'vendorCurrency',
    label: 'Currency',
    type: 'text',
    group: 'Basic Information',
    editable: true,
  },

  // Financial Details
  {
    key: 'invoiceNetAmount',
    label: 'Net Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
    required: true,
  },
  {
    key: 'invoiceTaxAmount',
    label: 'Tax Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'invoiceGrossAmount',
    label: 'Gross Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  {
    key: 'invoiceGrossAmountTotal',
    label: 'Total Gross Amount',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },
  { key: 'fxRate', label: 'FX Rate', type: 'number', group: 'Financial Details', editable: true },
  {
    key: 'translatedAmountEUR',
    label: 'Amount (EUR)',
    type: 'currency',
    group: 'Financial Details',
    editable: true,
  },

  // Service Details
  { key: 'feeType', label: 'Fee Type', type: 'text', group: 'Service Details', editable: true },
  {
    key: 'adminExpenses',
    label: 'Admin Expenses',
    type: 'text',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'descriptionPerInvoice',
    label: 'Invoice Description',
    type: 'textarea',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'descriptionService',
    label: 'Service Description',
    type: 'textarea',
    group: 'Service Details',
    editable: true,
  },
  {
    key: 'classificationForAccounting',
    label: 'Accounting Classification',
    type: 'text',
    group: 'Service Details',
    editable: true,
  },

  // Payment Information
  { key: 'paidBy', label: 'Paid By', type: 'text', group: 'Payment Information', editable: true },
  {
    key: 'amountPaid',
    label: 'Amount Paid',
    type: 'currency',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'paymentDate',
    label: 'Payment Date',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'sentToFinanceForPayment',
    label: 'Sent to Finance',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },
  {
    key: 'dateSentToAdministratorForPayment',
    label: 'Sent to Administrator',
    type: 'date',
    group: 'Payment Information',
    editable: true,
  },

  // VAT Information
  {
    key: 'reverseChargeVATPaidByFirm',
    label: 'Reverse Charge VAT',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatReturnEntity',
    label: 'VAT Return Entity',
    type: 'text',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatPaidByPanERO',
    label: 'VAT Paid by PanERO',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatReturnPeriod',
    label: 'VAT Return Period',
    type: 'text',
    group: 'VAT Information',
    editable: true,
  },
  {
    key: 'vatLiabilityAccruedAtEntity',
    label: 'VAT Liability Accrued',
    type: 'currency',
    group: 'VAT Information',
    editable: true,
  },

  // Approval & Comments
  {
    key: 'approvedBy',
    label: 'Approved By',
    type: 'text',
    group: 'Approval & Comments',
    editable: true,
  },
  {
    key: 'sentFinanceBy',
    label: 'Sent Finance By',
    type: 'text',
    group: 'Approval & Comments',
    editable: true,
  },
  { key: 'period', label: 'Period', type: 'text', group: 'Approval & Comments', editable: true },
  {
    key: 'financeComment',
    label: 'Finance Comment',
    type: 'textarea',
    group: 'Approval & Comments',
    editable: true,
  },
];
